server:
  port: 8000                                                                                                                                                                                                                                                                        
  servlet:
    context-path: /

# 5.7 com.mysql.jdbc.Driver
# 5.7 jdbc:mysql://localhost:3306/cos   
# jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: insta
    password: qwe125678
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234
      
  http:
      charset: UTF-8
      enabled: true
      force: true 
  

file:
  path: C:\workspace\insta\src\main\resources/upload/